
from fastapi import APIRouter

router = APIRouter(prefix="/api/screening", tags=["screening"])

screening_data = {
    "total_companies": 13,
    "qualified": [
        {
            "Company": "SalesForce",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": None,
            "Dividend Yield": "0.64%",
            "5-Years Growth": None,
            "Net Income": 6197,
            "Total Assets": 102928,
            "Total Equity": 61173,
            "EPS / Forecast": "3.25 / 2.86",
            "EBITDA": "11.14B",
            "1-Year Change": "-20.3%",
            "P/E Ratio": 34.97,
            "Debt / Equity": 0.1938,
            "Price/Book": 4,
            "Return on Equity": 0.1218,
            "Market Cap": "244.12B",
            "Gross Profit Margin": "77.7%"
        },
        {
            "Company": "ServiceNow Inc - 2024",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 10984,
            "Dividend Yield": 0,
            "5-Years Growth": None,
            "Net Income": 1425,
            "Total Assets": 20383,
            "Total Equity": 9609,
            "EPS / Forecast": "4.82 / 4.26",
            "EBITDA": "1.96B",
            "1-Year Change": "-30.3%",
            "P/E Ratio": 88.78,
            "Debt / Equity": 0.2125,
            "Price/Book": 14.26,
            "Return on Equity": 0.168,
            "Market Cap": "151.7B",
            "Gross Profit Margin": "78.1%"
        },
        {
            "Company": "Workday Inc - 2025",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 8446,
            "Dividend Yield": 0,
            "5-Years Growth": None,
            "Net Income": 526,
            "Total Assets": 17977,
            "Total Equity": 9034,
            "EPS / Forecast": "2.32 / 2.17",
            "EBITDA": "825.00M",
            "1-Year Change": "-17.6%",
            "P/E Ratio": 89.15,
            "Debt / Equity": 0.4272,
            "Price/Book": 6.39,
            "Return on Equity": 0.0734,
            "Market Cap": "55.17B",
            "Gross Profit Margin": "75.6%"
        },
        {
            "Company": "Snowflake Inc - 2025",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 3626.4,
            "Dividend Yield": 0,
            "5-Years Growth": None,
            "Net Income": -1285.64,
            "Total Assets": 9033.94,
            "Total Equity": 3006.64,
            "EPS / Forecast": "0.39 / 0.31",
            "EBITDA": "-1.31B",
            "1-Year Change": "39%",
            "P/E Ratio": -53.4,
            "Debt / Equity": 1.2591,
            "Price/Book": 34.53,
            "Return on Equity": -0.5309,
            "Market Cap": "76.58B",
            "Gross Profit Margin": "67.2%"
        },
        {
            "Company": "Amaze Holdings Inc - 2024",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 0.3,
            "Dividend Yield": 0,
            "5-Years Growth": None,
            "Net Income": -2.52,
            "Total Assets": 4.41,
            "Total Equity": 1.48,
            "EPS / Forecast": "-0.85 / --",
            "EBITDA": "-2.97M",
            "1-Year Change": "-97.5%",
            "P/E Ratio": -0.07,
            "Debt / Equity": 0.1162,
            "Price/Book": 0.04,
            "Return on Equity": -0.3605,
            "Market Cap": "8.02M",
            "Gross Profit Margin": "87%"
        },
        {
            "Company": "HubSpot",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": None,
            "Dividend Yield": 0,
            "5-Years Growth": None,
            "Net Income": 4.63,
            "Total Assets": 3795.83,
            "Total Equity": 1908.29,
            "EPS / Forecast": "2.67 / 2.59",
            "EBITDA": "26.19M",
            "1-Year Change": "-47.86%",
            "P/E Ratio": -5699.22,
            "Debt / Equity": 0.1465,
            "Price/Book": 10.84,
            "Return on Equity": -0.002,
            "Market Cap": None,
            "Gross Profit Margin": None
        },
        {
            "Company": "Apple Inc",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 416161,
            "Dividend Yield": "0.4%",
            "5-Years Growth": "5.11%",
            "Net Income": 112010,
            "Total Assets": 359241,
            "Total Equity": 73733,
            "EPS / Forecast": "1.85 / 1.76",
            "EBITDA": "144.75B",
            "1-Year Change": "7.2%",
            "P/E Ratio": 34.52,
            "Debt / Equity": 1.5241,
            "Price/Book": 54.47,
            "Return on Equity": 1.7142,
            "Market Cap": "3.83T",
            "Gross Profit Margin": "46.9%"
        },
        {
            "Company": "Palantir",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": None,
            "Dividend Yield": 0,
            "5-Years Growth": None,
            "Net Income": 462.19,
            "Total Assets": 6340.88,
            "Total Equity": 5094.41,
            "EPS / Forecast": "0.4317",
            "EBITDA": "875.8M",
            "1-Year Change": "159.15%",
            "P/E Ratio": 423.49,
            "Debt / Equity": 0.0352,
            "Price/Book": 64.34,
            "Return on Equity": 0.195,
            "Market Cap": "421.53B",
            "Gross Profit Margin": "80.8%"
        },
        {
            "Company": "Microsoft Corporation",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 281724,
            "Dividend Yield": "0.8%",
            "5-Years Growth": "10.22%",
            "Net Income": 101832,
            "Total Assets": 619003,
            "Total Equity": 343479,
            "EPS / Forecast": "4.13 / 3.66",
            "EBITDA": "156.53B",
            "1-Year Change": "13.4%",
            "P/E Ratio": 34.47,
            "Debt / Equity": 0.3315,
            "Price/Book": 10.53,
            "Return on Equity": 0.3224,
            "Market Cap": "3.55T",
            "Gross Profit Margin": "68.8%"
        },
        {
            "Company": "Googl",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": None,
            "Dividend Yield": "0.26%",
            "5-Years Growth": None,
            "Net Income": 100118,
            "Total Assets": 450256,
            "Total Equity": 325084,
            "EPS / Forecast": "10.1351",
            "EBITDA": "129.50B",
            "1-Year Change": "67.8%",
            "P/E Ratio": 32.05,
            "Debt / Equity": 0.1142,
            "Price/Book": 8.88,
            "Return on Equity": 0.3545,
            "Market Cap": "3.93T",
            "Gross Profit Margin": "59.2%"
        },
        {
            "Company": "International Business Machines (IBM) - 2024",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 62753,
            "Dividend Yield": "2.22%",
            "5-Years Growth": "0.61%",
            "Net Income": 6023,
            "Total Assets": 137175,
            "Total Equity": 27393,
            "EPS / Forecast": "2.65 / 2.44",
            "EBITDA": "12.89B",
            "1-Year Change": "39.1%",
            "P/E Ratio": 36.13,
            "Debt / Equity": 2.3783,
            "Price/Book": 10.36,
            "Return on Equity": 0.3016,
            "Market Cap": "283B",
            "Gross Profit Margin": "57.8%"
        },
        {
            "Company": "Uber Technologies Inc",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 43978,
            "Dividend Yield": 0,
            "5-Years Growth": None,
            "Net Income": 9856,
            "Total Assets": 51244,
            "Total Equity": 22476,
            "EPS / Forecast": "1.20 / 0.69",
            "EBITDA": "5.29B",
            "1-Year Change": "34.91%",
            "P/E Ratio": 11.17,
            "Debt / Equity": 0.4576,
            "Price/Book": 6.47,
            "Return on Equity": 0.7299,
            "Market Cap": "182B",
            "Gross Profit Margin": "34.2%"
        },
        {
            "Company": "The Trade Desk",
            "Country": "US",
            "Sector": "Technology",
            "Industry": "Software & IT Services",
            "Revenue": 2444.83,
            "Dividend Yield": 0,
            "5-Years Growth": None,
            "Net Income": 393.08,
            "Total Assets": 6111.95,
            "Total Equity": 2949.15,
            "EPS / Forecast": "0.45 / 0.20",
            "EBITDA": "498.66M",
            "1-Year Change": "-69.32%",
            "P/E Ratio": 43.84,
            "Debt / Equity": 0.1446,
            "Price/Book": 7.02,
            "Return on Equity": 0.1678,
            "Market Cap": "18.04B",
            "Gross Profit Margin": "78.8%"
        }
    ]
}

@router.get("/companies")
async def get_screening_companies():
    return screening_data

